version: 0.2
phases:
  install:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered build phase
      - mvn clean prepare-package jar
  post_build:
    commands:
      - echo Entered the post-build phase
artifacts:
  files:
    - AuthorizationMicroserivce.jar